// src/app.ts
import { toNodeHandler } from "better-auth/node";
import express from "express";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": 'model User {\n  id            String    @id\n  name          String\n  email         String\n  emailVerified Boolean   @default(false)\n  image         String?\n  createdAt     DateTime  @default(now())\n  updatedAt     DateTime  @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n\n  role   String  @default("USER")\n  phone  String?\n  status String? @default("ACTIVE")\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nmodel Availability {\n  id      String @id @default(uuid())\n  tutorId String\n\n  day       String\n  startTime DateTime\n  endTime   DateTime\n\n  isBooked Boolean @default(false)\n\n  tutor Tutor @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n}\n\nmodel Booking {\n  id String @id @default(uuid())\n\n  studentId  String\n  tutorId    String\n  categoryId String\n\n  date      DateTime\n  startTime DateTime\n  endTime   DateTime\n\n  status BookingStatus @default(CONFIRMED)\n\n  tutor    Tutor    @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  category Category @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n\n  review    Review?\n  createdAt DateTime @default(now())\n}\n\nenum BookingStatus {\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nmodel Category {\n  id          String  @id @default(uuid())\n  name        String  @unique\n  description String?\n\n  tutors   TutorSubject[]\n  bookings Booking[]\n\n  createdAt DateTime @default(now())\n}\n\nmodel Review {\n  id String @id @default(uuid())\n\n  bookingId String @unique\n  studentId String\n  tutorId   String\n\n  rating  Int\n  comment String?\n\n  booking Booking @relation(fields: [bookingId], references: [id])\n  tutor   Tutor   @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n\n  createdAt DateTime @default(now())\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel Tutor {\n  id         String  @id @default(uuid())\n  userId     String  @unique\n  bio        String?\n  hourlyRate Float\n  experience Int?\n  isFeatured Boolean @default(false)\n\n  subjects     TutorSubject[]\n  availability Availability[]\n  reviews      Review[]\n  bookings     Booking[]\n\n  ratingAvg Float @default(0)\n\n  createdAt DateTime @default(now())\n}\n\nmodel TutorSubject {\n  id String @id @default(uuid())\n\n  tutorId    String\n  categoryId String\n\n  tutor    Tutor    @relation(fields: [tutorId], references: [id], onDelete: Cascade)\n  category Category @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n\n  @@unique([tutorId, categoryId])\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"role","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"scalar","type":"String"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"},"Availability":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"day","kind":"scalar","type":"String"},{"name":"startTime","kind":"scalar","type":"DateTime"},{"name":"endTime","kind":"scalar","type":"DateTime"},{"name":"isBooked","kind":"scalar","type":"Boolean"},{"name":"tutor","kind":"object","type":"Tutor","relationName":"AvailabilityToTutor"}],"dbName":null},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"date","kind":"scalar","type":"DateTime"},{"name":"startTime","kind":"scalar","type":"DateTime"},{"name":"endTime","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"tutor","kind":"object","type":"Tutor","relationName":"BookingToTutor"},{"name":"category","kind":"object","type":"Category","relationName":"BookingToCategory"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"tutors","kind":"object","type":"TutorSubject","relationName":"CategoryToTutorSubject"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToCategory"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"},{"name":"tutor","kind":"object","type":"Tutor","relationName":"ReviewToTutor"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Tutor":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Float"},{"name":"experience","kind":"scalar","type":"Int"},{"name":"isFeatured","kind":"scalar","type":"Boolean"},{"name":"subjects","kind":"object","type":"TutorSubject","relationName":"TutorToTutorSubject"},{"name":"availability","kind":"object","type":"Availability","relationName":"AvailabilityToTutor"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToTutor"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToTutor"},{"name":"ratingAvg","kind":"scalar","type":"Float"},{"name":"createdAt","kind":"scalar","type":"DateTime"}],"dbName":null},"TutorSubject":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"Tutor","relationName":"TutorToTutorSubject"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorSubject"}],"dbName":null}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","_count","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","tutor","tutors","category","booking","review","bookings","subjects","availability","reviews","Availability.findUnique","Availability.findUniqueOrThrow","Availability.findFirst","Availability.findFirstOrThrow","Availability.findMany","Availability.createOne","Availability.createMany","Availability.createManyAndReturn","Availability.updateOne","Availability.updateMany","Availability.updateManyAndReturn","Availability.upsertOne","Availability.deleteOne","Availability.deleteMany","Availability.groupBy","Availability.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","_avg","_sum","Review.groupBy","Review.aggregate","Tutor.findUnique","Tutor.findUniqueOrThrow","Tutor.findFirst","Tutor.findFirstOrThrow","Tutor.findMany","Tutor.createOne","Tutor.createMany","Tutor.createManyAndReturn","Tutor.updateOne","Tutor.updateMany","Tutor.updateManyAndReturn","Tutor.upsertOne","Tutor.deleteOne","Tutor.deleteMany","Tutor.groupBy","Tutor.aggregate","TutorSubject.findUnique","TutorSubject.findUniqueOrThrow","TutorSubject.findFirst","TutorSubject.findFirstOrThrow","TutorSubject.findMany","TutorSubject.createOne","TutorSubject.createMany","TutorSubject.createManyAndReturn","TutorSubject.updateOne","TutorSubject.updateMany","TutorSubject.updateManyAndReturn","TutorSubject.upsertOne","TutorSubject.deleteOne","TutorSubject.deleteMany","TutorSubject.groupBy","TutorSubject.aggregate","AND","OR","NOT","id","tutorId","categoryId","equals","in","notIn","lt","lte","gt","gte","contains","startsWith","endsWith","not","userId","bio","hourlyRate","experience","isFeatured","ratingAvg","createdAt","every","some","none","bookingId","studentId","rating","comment","name","description","date","startTime","endTime","BookingStatus","status","day","isBooked","tutorId_categoryId","identifier","value","expiresAt","updatedAt","accountId","providerId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","email","emailVerified","image","role","phone","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "vwRYoAEPBAAAywIAIAUAAMwCACC4AQAAygIAMLkBAAAOABC6AQAAygIAMLsBAQAAAAHPAUAAqAIAIdcBAQCjAgAh3QEBAKQCACHkAUAAqAIAIfEBAQAAAAHyASAApwIAIfMBAQCkAgAh9AEBAKMCACH1AQEApAIAIQEAAAABACAMAwAAzwIAILgBAADQAgAwuQEAAAMAELoBAADQAgAwuwEBAKMCACHJAQEAowIAIc8BQACoAgAh4wFAAKgCACHkAUAAqAIAIe4BAQCjAgAh7wEBAKQCACHwAQEApAIAIQMDAACKBAAg7wEAANkCACDwAQAA2QIAIAwDAADPAgAguAEAANACADC5AQAAAwAQugEAANACADC7AQEAAAAByQEBAKMCACHPAUAAqAIAIeMBQACoAgAh5AFAAKgCACHuAQEAAAAB7wEBAKQCACHwAQEApAIAIQMAAAADACABAAAEADACAAAFACARAwAAzwIAILgBAADNAgAwuQEAAAcAELoBAADNAgAwuwEBAKMCACHJAQEAowIAIc8BQACoAgAh5AFAAKgCACHlAQEAowIAIeYBAQCjAgAh5wEBAKQCACHoAQEApAIAIekBAQCkAgAh6gFAAM4CACHrAUAAzgIAIewBAQCkAgAh7QEBAKQCACEIAwAAigQAIOcBAADZAgAg6AEAANkCACDpAQAA2QIAIOoBAADZAgAg6wEAANkCACDsAQAA2QIAIO0BAADZAgAgEQMAAM8CACC4AQAAzQIAMLkBAAAHABC6AQAAzQIAMLsBAQAAAAHJAQEAowIAIc8BQACoAgAh5AFAAKgCACHlAQEAowIAIeYBAQCjAgAh5wEBAKQCACHoAQEApAIAIekBAQCkAgAh6gFAAM4CACHrAUAAzgIAIewBAQCkAgAh7QEBAKQCACEDAAAABwAgAQAACAAwAgAACQAgAQAAAAMAIAEAAAAHACABAAAAAQAgDwQAAMsCACAFAADMAgAguAEAAMoCADC5AQAADgAQugEAAMoCADC7AQEAowIAIc8BQACoAgAh1wEBAKMCACHdAQEApAIAIeQBQACoAgAh8QEBAKMCACHyASAApwIAIfMBAQCkAgAh9AEBAKMCACH1AQEApAIAIQUEAACIBAAgBQAAiQQAIN0BAADZAgAg8wEAANkCACD1AQAA2QIAIAMAAAAOACABAAAPADACAAABACADAAAADgAgAQAADwAwAgAAAQAgAwAAAA4AIAEAAA8AMAIAAAEAIAwEAACGBAAgBQAAhwQAILsBAQAAAAHPAUAAAAAB1wEBAAAAAd0BAQAAAAHkAUAAAAAB8QEBAAAAAfIBIAAAAAHzAQEAAAAB9AEBAAAAAfUBAQAAAAEBDAAAEwAgCrsBAQAAAAHPAUAAAAAB1wEBAAAAAd0BAQAAAAHkAUAAAAAB8QEBAAAAAfIBIAAAAAHzAQEAAAAB9AEBAAAAAfUBAQAAAAEBDAAAFQAwAQwAABUAMAwEAADsAwAgBQAA7QMAILsBAQDUAgAhzwFAAOMCACHXAQEA1AIAId0BAQDfAgAh5AFAAOMCACHxAQEA1AIAIfIBIADiAgAh8wEBAN8CACH0AQEA1AIAIfUBAQDfAgAhAgAAAAEAIAwAABgAIAq7AQEA1AIAIc8BQADjAgAh1wEBANQCACHdAQEA3wIAIeQBQADjAgAh8QEBANQCACHyASAA4gIAIfMBAQDfAgAh9AEBANQCACH1AQEA3wIAIQIAAAAOACAMAAAaACACAAAADgAgDAAAGgAgAwAAAAEAIBMAABMAIBQAABgAIAEAAAABACABAAAADgAgBgYAAOkDACAZAADrAwAgGgAA6gMAIN0BAADZAgAg8wEAANkCACD1AQAA2QIAIA24AQAAyQIAMLkBAAAhABC6AQAAyQIAMLsBAQCNAgAhzwFAAJYCACHXAQEAjQIAId0BAQCSAgAh5AFAAJYCACHxAQEAjQIAIfIBIACVAgAh8wEBAJICACH0AQEAjQIAIfUBAQCSAgAhAwAAAA4AIAEAACAAMBgAACEAIAMAAAAOACABAAAPADACAAABACABAAAABQAgAQAAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAkDAADoAwAguwEBAAAAAckBAQAAAAHPAUAAAAAB4wFAAAAAAeQBQAAAAAHuAQEAAAAB7wEBAAAAAfABAQAAAAEBDAAAKQAgCLsBAQAAAAHJAQEAAAABzwFAAAAAAeMBQAAAAAHkAUAAAAAB7gEBAAAAAe8BAQAAAAHwAQEAAAABAQwAACsAMAEMAAArADAJAwAA5wMAILsBAQDUAgAhyQEBANQCACHPAUAA4wIAIeMBQADjAgAh5AFAAOMCACHuAQEA1AIAIe8BAQDfAgAh8AEBAN8CACECAAAABQAgDAAALgAgCLsBAQDUAgAhyQEBANQCACHPAUAA4wIAIeMBQADjAgAh5AFAAOMCACHuAQEA1AIAIe8BAQDfAgAh8AEBAN8CACECAAAAAwAgDAAAMAAgAgAAAAMAIAwAADAAIAMAAAAFACATAAApACAUAAAuACABAAAABQAgAQAAAAMAIAUGAADkAwAgGQAA5gMAIBoAAOUDACDvAQAA2QIAIPABAADZAgAgC7gBAADIAgAwuQEAADcAELoBAADIAgAwuwEBAI0CACHJAQEAjQIAIc8BQACWAgAh4wFAAJYCACHkAUAAlgIAIe4BAQCNAgAh7wEBAJICACHwAQEAkgIAIQMAAAADACABAAA2ADAYAAA3ACADAAAAAwAgAQAABAAwAgAABQAgAQAAAAkAIAEAAAAJACADAAAABwAgAQAACAAwAgAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACAOAwAA4wMAILsBAQAAAAHJAQEAAAABzwFAAAAAAeQBQAAAAAHlAQEAAAAB5gEBAAAAAecBAQAAAAHoAQEAAAAB6QEBAAAAAeoBQAAAAAHrAUAAAAAB7AEBAAAAAe0BAQAAAAEBDAAAPwAgDbsBAQAAAAHJAQEAAAABzwFAAAAAAeQBQAAAAAHlAQEAAAAB5gEBAAAAAecBAQAAAAHoAQEAAAAB6QEBAAAAAeoBQAAAAAHrAUAAAAAB7AEBAAAAAe0BAQAAAAEBDAAAQQAwAQwAAEEAMA4DAADiAwAguwEBANQCACHJAQEA1AIAIc8BQADjAgAh5AFAAOMCACHlAQEA1AIAIeYBAQDUAgAh5wEBAN8CACHoAQEA3wIAIekBAQDfAgAh6gFAAOEDACHrAUAA4QMAIewBAQDfAgAh7QEBAN8CACECAAAACQAgDAAARAAgDbsBAQDUAgAhyQEBANQCACHPAUAA4wIAIeQBQADjAgAh5QEBANQCACHmAQEA1AIAIecBAQDfAgAh6AEBAN8CACHpAQEA3wIAIeoBQADhAwAh6wFAAOEDACHsAQEA3wIAIe0BAQDfAgAhAgAAAAcAIAwAAEYAIAIAAAAHACAMAABGACADAAAACQAgEwAAPwAgFAAARAAgAQAAAAkAIAEAAAAHACAKBgAA3gMAIBkAAOADACAaAADfAwAg5wEAANkCACDoAQAA2QIAIOkBAADZAgAg6gEAANkCACDrAQAA2QIAIOwBAADZAgAg7QEAANkCACAQuAEAAMQCADC5AQAATQAQugEAAMQCADC7AQEAjQIAIckBAQCNAgAhzwFAAJYCACHkAUAAlgIAIeUBAQCNAgAh5gEBAI0CACHnAQEAkgIAIegBAQCSAgAh6QEBAJICACHqAUAAxQIAIesBQADFAgAh7AEBAJICACHtAQEAkgIAIQMAAAAHACABAABMADAYAABNACADAAAABwAgAQAACAAwAgAACQAgCbgBAADDAgAwuQEAAFMAELoBAADDAgAwuwEBAAAAAc8BQACoAgAh4QEBAKMCACHiAQEAowIAIeMBQACoAgAh5AFAAKgCACEBAAAAUAAgAQAAAFAAIAm4AQAAwwIAMLkBAABTABC6AQAAwwIAMLsBAQCjAgAhzwFAAKgCACHhAQEAowIAIeIBAQCjAgAh4wFAAKgCACHkAUAAqAIAIQADAAAAUwAgAQAAVAAwAgAAUAAgAwAAAFMAIAEAAFQAMAIAAFAAIAMAAABTACABAABUADACAABQACAGuwEBAAAAAc8BQAAAAAHhAQEAAAAB4gEBAAAAAeMBQAAAAAHkAUAAAAABAQwAAFgAIAa7AQEAAAABzwFAAAAAAeEBAQAAAAHiAQEAAAAB4wFAAAAAAeQBQAAAAAEBDAAAWgAwAQwAAFoAMAa7AQEA1AIAIc8BQADjAgAh4QEBANQCACHiAQEA1AIAIeMBQADjAgAh5AFAAOMCACECAAAAUAAgDAAAXQAgBrsBAQDUAgAhzwFAAOMCACHhAQEA1AIAIeIBAQDUAgAh4wFAAOMCACHkAUAA4wIAIQIAAABTACAMAABfACACAAAAUwAgDAAAXwAgAwAAAFAAIBMAAFgAIBQAAF0AIAEAAABQACABAAAAUwAgAwYAANsDACAZAADdAwAgGgAA3AMAIAm4AQAAwgIAMLkBAABmABC6AQAAwgIAMLsBAQCNAgAhzwFAAJYCACHhAQEAjQIAIeIBAQCNAgAh4wFAAJYCACHkAUAAlgIAIQMAAABTACABAABlADAYAABmACADAAAAUwAgAQAAVAAwAgAAUAAgCk0AALoCACC4AQAAuwIAMLkBAAB4ABC6AQAAuwIAMLsBAQAAAAG8AQEAowIAIdoBQACoAgAh2wFAAKgCACHeAQEAowIAId8BIACnAgAhAQAAAGkAIAhNAAC6AgAgTwAAvgIAILgBAADBAgAwuQEAAGsAELoBAADBAgAwuwEBAKMCACG8AQEAowIAIb0BAQCjAgAhAk0AANgDACBPAADZAwAgCU0AALoCACBPAAC-AgAguAEAAMECADC5AQAAawAQugEAAMECADC7AQEAAAABvAEBAKMCACG9AQEAowIAIeABAADAAgAgAwAAAGsAIAEAAGwAMAIAAG0AIAMAAABrACABAABsADACAABtACAPTQAAugIAIE8AAL4CACBRAAC_AgAguAEAALwCADC5AQAAcAAQugEAALwCADC7AQEAowIAIbwBAQCjAgAhvQEBAKMCACHPAUAAqAIAIdQBAQCjAgAh2QFAAKgCACHaAUAAqAIAIdsBQACoAgAh3QEAAL0C3QEiA00AANgDACBPAADZAwAgUQAA2gMAIA9NAAC6AgAgTwAAvgIAIFEAAL8CACC4AQAAvAIAMLkBAABwABC6AQAAvAIAMLsBAQAAAAG8AQEAowIAIb0BAQCjAgAhzwFAAKgCACHUAQEAowIAIdkBQACoAgAh2gFAAKgCACHbAUAAqAIAId0BAAC9At0BIgMAAABwACABAABxADACAAByACAMTQAAugIAIFAAALkCACC4AQAAtwIAMLkBAAB0ABC6AQAAtwIAMLsBAQCjAgAhvAEBAKMCACHPAUAAqAIAIdMBAQCjAgAh1AEBAKMCACHVAQIAuAIAIdYBAQCkAgAhAQAAAHQAIAEAAABrACABAAAAcAAgCk0AALoCACC4AQAAuwIAMLkBAAB4ABC6AQAAuwIAMLsBAQCjAgAhvAEBAKMCACHaAUAAqAIAIdsBQACoAgAh3gEBAKMCACHfASAApwIAIQFNAADYAwAgAwAAAHgAIAEAAHkAMAIAAGkAIANNAADYAwAgUAAA1wMAINYBAADZAgAgDE0AALoCACBQAAC5AgAguAEAALcCADC5AQAAdAAQugEAALcCADC7AQEAAAABvAEBAKMCACHPAUAAqAIAIdMBAQAAAAHUAQEAowIAIdUBAgC4AgAh1gEBAKQCACEDAAAAdAAgAQAAewAwAgAAfAAgAwAAAHAAIAEAAHEAMAIAAHIAIAEAAABrACABAAAAeAAgAQAAAHQAIAEAAABwACABAAAAaQAgAwAAAHgAIAEAAHkAMAIAAGkAIAMAAAB4ACABAAB5ADACAABpACADAAAAeAAgAQAAeQAwAgAAaQAgB00AANYDACC7AQEAAAABvAEBAAAAAdoBQAAAAAHbAUAAAAAB3gEBAAAAAd8BIAAAAAEBDAAAhwEAIAa7AQEAAAABvAEBAAAAAdoBQAAAAAHbAUAAAAAB3gEBAAAAAd8BIAAAAAEBDAAAiQEAMAEMAACJAQAwB00AANUDACC7AQEA1AIAIbwBAQDUAgAh2gFAAOMCACHbAUAA4wIAId4BAQDUAgAh3wEgAOICACECAAAAaQAgDAAAjAEAIAa7AQEA1AIAIbwBAQDUAgAh2gFAAOMCACHbAUAA4wIAId4BAQDUAgAh3wEgAOICACECAAAAeAAgDAAAjgEAIAIAAAB4ACAMAACOAQAgAwAAAGkAIBMAAIcBACAUAACMAQAgAQAAAGkAIAEAAAB4ACADBgAA0gMAIBkAANQDACAaAADTAwAgCbgBAAC2AgAwuQEAAJUBABC6AQAAtgIAMLsBAQCNAgAhvAEBAI0CACHaAUAAlgIAIdsBQACWAgAh3gEBAI0CACHfASAAlQIAIQMAAAB4ACABAACUAQAwGAAAlQEAIAMAAAB4ACABAAB5ADACAABpACABAAAAcgAgAQAAAHIAIAMAAABwACABAABxADACAAByACADAAAAcAAgAQAAcQAwAgAAcgAgAwAAAHAAIAEAAHEAMAIAAHIAIAxNAADDAwAgTwAA_wIAIFEAAIADACC7AQEAAAABvAEBAAAAAb0BAQAAAAHPAUAAAAAB1AEBAAAAAdkBQAAAAAHaAUAAAAAB2wFAAAAAAd0BAAAA3QECAQwAAJ0BACAJuwEBAAAAAbwBAQAAAAG9AQEAAAABzwFAAAAAAdQBAQAAAAHZAUAAAAAB2gFAAAAAAdsBQAAAAAHdAQAAAN0BAgEMAACfAQAwAQwAAJ8BADAMTQAAwQMAIE8AAPQCACBRAAD1AgAguwEBANQCACG8AQEA1AIAIb0BAQDUAgAhzwFAAOMCACHUAQEA1AIAIdkBQADjAgAh2gFAAOMCACHbAUAA4wIAId0BAADyAt0BIgIAAAByACAMAACiAQAgCbsBAQDUAgAhvAEBANQCACG9AQEA1AIAIc8BQADjAgAh1AEBANQCACHZAUAA4wIAIdoBQADjAgAh2wFAAOMCACHdAQAA8gLdASICAAAAcAAgDAAApAEAIAIAAABwACAMAACkAQAgAwAAAHIAIBMAAJ0BACAUAACiAQAgAQAAAHIAIAEAAABwACADBgAAzwMAIBkAANEDACAaAADQAwAgDLgBAACyAgAwuQEAAKsBABC6AQAAsgIAMLsBAQCNAgAhvAEBAI0CACG9AQEAjQIAIc8BQACWAgAh1AEBAI0CACHZAUAAlgIAIdoBQACWAgAh2wFAAJYCACHdAQAAswLdASIDAAAAcAAgAQAAqgEAMBgAAKsBACADAAAAcAAgAQAAcQAwAgAAcgAgCU4AAKkCACBSAACsAgAguAEAALECADC5AQAAsQEAELoBAACxAgAwuwEBAAAAAc8BQACoAgAh1wEBAAAAAdgBAQCkAgAhAQAAAK4BACABAAAArgEAIAlOAACpAgAgUgAArAIAILgBAACxAgAwuQEAALEBABC6AQAAsQIAMLsBAQCjAgAhzwFAAKgCACHXAQEAowIAIdgBAQCkAgAhA04AAKsDACBSAACuAwAg2AEAANkCACADAAAAsQEAIAEAALIBADACAACuAQAgAwAAALEBACABAACyAQAwAgAArgEAIAMAAACxAQAgAQAAsgEAMAIAAK4BACAGTgAAzQMAIFIAAM4DACC7AQEAAAABzwFAAAAAAdcBAQAAAAHYAQEAAAABAQwAALYBACAEuwEBAAAAAc8BQAAAAAHXAQEAAAAB2AEBAAAAAQEMAAC4AQAwAQwAALgBADAGTgAAtwMAIFIAALgDACC7AQEA1AIAIc8BQADjAgAh1wEBANQCACHYAQEA3wIAIQIAAACuAQAgDAAAuwEAIAS7AQEA1AIAIc8BQADjAgAh1wEBANQCACHYAQEA3wIAIQIAAACxAQAgDAAAvQEAIAIAAACxAQAgDAAAvQEAIAMAAACuAQAgEwAAtgEAIBQAALsBACABAAAArgEAIAEAAACxAQAgBAYAALQDACAZAAC2AwAgGgAAtQMAINgBAADZAgAgB7gBAACwAgAwuQEAAMQBABC6AQAAsAIAMLsBAQCNAgAhzwFAAJYCACHXAQEAjQIAIdgBAQCSAgAhAwAAALEBACABAADDAQAwGAAAxAEAIAMAAACxAQAgAQAAsgEAMAIAAK4BACABAAAAfAAgAQAAAHwAIAMAAAB0ACABAAB7ADACAAB8ACADAAAAdAAgAQAAewAwAgAAfAAgAwAAAHQAIAEAAHsAMAIAAHwAIAlNAAD9AgAgUAAAjgMAILsBAQAAAAG8AQEAAAABzwFAAAAAAdMBAQAAAAHUAQEAAAAB1QECAAAAAdYBAQAAAAEBDAAAzAEAIAe7AQEAAAABvAEBAAAAAc8BQAAAAAHTAQEAAAAB1AEBAAAAAdUBAgAAAAHWAQEAAAABAQwAAM4BADABDAAAzgEAMAlNAAD8AgAgUAAAjAMAILsBAQDUAgAhvAEBANQCACHPAUAA4wIAIdMBAQDUAgAh1AEBANQCACHVAQIA-wIAIdYBAQDfAgAhAgAAAHwAIAwAANEBACAHuwEBANQCACG8AQEA1AIAIc8BQADjAgAh0wEBANQCACHUAQEA1AIAIdUBAgD7AgAh1gEBAN8CACECAAAAdAAgDAAA0wEAIAIAAAB0ACAMAADTAQAgAwAAAHwAIBMAAMwBACAUAADRAQAgAQAAAHwAIAEAAAB0ACAGBgAArwMAIBkAALIDACAaAACxAwAglAEAALADACCVAQAAswMAINYBAADZAgAgCrgBAACtAgAwuQEAANoBABC6AQAArQIAMLsBAQCNAgAhvAEBAI0CACHPAUAAlgIAIdMBAQCNAgAh1AEBAI0CACHVAQIArgIAIdYBAQCSAgAhAwAAAHQAIAEAANkBADAYAADaAQAgAwAAAHQAIAEAAHsAMAIAAHwAIA9SAACsAgAgUwAAqQIAIFQAAKoCACBVAACrAgAguAEAAKICADC5AQAA4AEAELoBAACiAgAwuwEBAAAAAckBAQAAAAHKAQEApAIAIcsBCAClAgAhzAECAKYCACHNASAApwIAIc4BCAClAgAhzwFAAKgCACEBAAAA3QEAIAEAAADdAQAgD1IAAKwCACBTAACpAgAgVAAAqgIAIFUAAKsCACC4AQAAogIAMLkBAADgAQAQugEAAKICADC7AQEAowIAIckBAQCjAgAhygEBAKQCACHLAQgApQIAIcwBAgCmAgAhzQEgAKcCACHOAQgApQIAIc8BQACoAgAhBlIAAK4DACBTAACrAwAgVAAArAMAIFUAAK0DACDKAQAA2QIAIMwBAADZAgAgAwAAAOABACABAADhAQAwAgAA3QEAIAMAAADgAQAgAQAA4QEAMAIAAN0BACADAAAA4AEAIAEAAOEBADACAADdAQAgDFIAAKoDACBTAACnAwAgVAAAqAMAIFUAAKkDACC7AQEAAAAByQEBAAAAAcoBAQAAAAHLAQgAAAABzAECAAAAAc0BIAAAAAHOAQgAAAABzwFAAAAAAQEMAADlAQAgCLsBAQAAAAHJAQEAAAABygEBAAAAAcsBCAAAAAHMAQIAAAABzQEgAAAAAc4BCAAAAAHPAUAAAAABAQwAAOcBADABDAAA5wEAMAxSAADnAgAgUwAA5AIAIFQAAOUCACBVAADmAgAguwEBANQCACHJAQEA1AIAIcoBAQDfAgAhywEIAOACACHMAQIA4QIAIc0BIADiAgAhzgEIAOACACHPAUAA4wIAIQIAAADdAQAgDAAA6gEAIAi7AQEA1AIAIckBAQDUAgAhygEBAN8CACHLAQgA4AIAIcwBAgDhAgAhzQEgAOICACHOAQgA4AIAIc8BQADjAgAhAgAAAOABACAMAADsAQAgAgAAAOABACAMAADsAQAgAwAAAN0BACATAADlAQAgFAAA6gEAIAEAAADdAQAgAQAAAOABACAHBgAA2gIAIBkAAN0CACAaAADcAgAglAEAANsCACCVAQAA3gIAIMoBAADZAgAgzAEAANkCACALuAEAAJECADC5AQAA8wEAELoBAACRAgAwuwEBAI0CACHJAQEAjQIAIcoBAQCSAgAhywEIAJMCACHMAQIAlAIAIc0BIACVAgAhzgEIAJMCACHPAUAAlgIAIQMAAADgAQAgAQAA8gEAMBgAAPMBACADAAAA4AEAIAEAAOEBADACAADdAQAgAQAAAG0AIAEAAABtACADAAAAawAgAQAAbAAwAgAAbQAgAwAAAGsAIAEAAGwAMAIAAG0AIAMAAABrACABAABsADACAABtACAFTQAA1wIAIE8AANgCACC7AQEAAAABvAEBAAAAAb0BAQAAAAEBDAAA-wEAIAO7AQEAAAABvAEBAAAAAb0BAQAAAAEBDAAA_QEAMAEMAAD9AQAwBU0AANUCACBPAADWAgAguwEBANQCACG8AQEA1AIAIb0BAQDUAgAhAgAAAG0AIAwAAIACACADuwEBANQCACG8AQEA1AIAIb0BAQDUAgAhAgAAAGsAIAwAAIICACACAAAAawAgDAAAggIAIAMAAABtACATAAD7AQAgFAAAgAIAIAEAAABtACABAAAAawAgAwYAANECACAZAADTAgAgGgAA0gIAIAa4AQAAjAIAMLkBAACJAgAQugEAAIwCADC7AQEAjQIAIbwBAQCNAgAhvQEBAI0CACEDAAAAawAgAQAAiAIAMBgAAIkCACADAAAAawAgAQAAbAAwAgAAbQAgBrgBAACMAgAwuQEAAIkCABC6AQAAjAIAMLsBAQCNAgAhvAEBAI0CACG9AQEAjQIAIQ4GAACPAgAgGQAAkAIAIBoAAJACACC-AQEAAAABvwEBAAAABMABAQAAAATBAQEAAAABwgEBAAAAAcMBAQAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAI4CACEOBgAAjwIAIBkAAJACACAaAACQAgAgvgEBAAAAAb8BAQAAAATAAQEAAAAEwQEBAAAAAcIBAQAAAAHDAQEAAAABxAEBAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQCOAgAhCL4BAgAAAAG_AQIAAAAEwAECAAAABMEBAgAAAAHCAQIAAAABwwECAAAAAcQBAgAAAAHIAQIAjwIAIQu-AQEAAAABvwEBAAAABMABAQAAAATBAQEAAAABwgEBAAAAAcMBAQAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAJACACELuAEAAJECADC5AQAA8wEAELoBAACRAgAwuwEBAI0CACHJAQEAjQIAIcoBAQCSAgAhywEIAJMCACHMAQIAlAIAIc0BIACVAgAhzgEIAJMCACHPAUAAlgIAIQ4GAACcAgAgGQAAoQIAIBoAAKECACC-AQEAAAABvwEBAAAABcABAQAAAAXBAQEAAAABwgEBAAAAAcMBAQAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAKACACENBgAAjwIAIBkAAJ8CACAaAACfAgAglAEAAJ8CACCVAQAAnwIAIL4BCAAAAAG_AQgAAAAEwAEIAAAABMEBCAAAAAHCAQgAAAABwwEIAAAAAcQBCAAAAAHIAQgAngIAIQ0GAACcAgAgGQAAnAIAIBoAAJwCACCUAQAAnQIAIJUBAACcAgAgvgECAAAAAb8BAgAAAAXAAQIAAAAFwQECAAAAAcIBAgAAAAHDAQIAAAABxAECAAAAAcgBAgCbAgAhBQYAAI8CACAZAACaAgAgGgAAmgIAIL4BIAAAAAHIASAAmQIAIQsGAACPAgAgGQAAmAIAIBoAAJgCACC-AUAAAAABvwFAAAAABMABQAAAAATBAUAAAAABwgFAAAAAAcMBQAAAAAHEAUAAAAAByAFAAJcCACELBgAAjwIAIBkAAJgCACAaAACYAgAgvgFAAAAAAb8BQAAAAATAAUAAAAAEwQFAAAAAAcIBQAAAAAHDAUAAAAABxAFAAAAAAcgBQACXAgAhCL4BQAAAAAG_AUAAAAAEwAFAAAAABMEBQAAAAAHCAUAAAAABwwFAAAAAAcQBQAAAAAHIAUAAmAIAIQUGAACPAgAgGQAAmgIAIBoAAJoCACC-ASAAAAAByAEgAJkCACECvgEgAAAAAcgBIACaAgAhDQYAAJwCACAZAACcAgAgGgAAnAIAIJQBAACdAgAglQEAAJwCACC-AQIAAAABvwECAAAABcABAgAAAAXBAQIAAAABwgECAAAAAcMBAgAAAAHEAQIAAAAByAECAJsCACEIvgECAAAAAb8BAgAAAAXAAQIAAAAFwQECAAAAAcIBAgAAAAHDAQIAAAABxAECAAAAAcgBAgCcAgAhCL4BCAAAAAG_AQgAAAAFwAEIAAAABcEBCAAAAAHCAQgAAAABwwEIAAAAAcQBCAAAAAHIAQgAnQIAIQ0GAACPAgAgGQAAnwIAIBoAAJ8CACCUAQAAnwIAIJUBAACfAgAgvgEIAAAAAb8BCAAAAATAAQgAAAAEwQEIAAAAAcIBCAAAAAHDAQgAAAABxAEIAAAAAcgBCACeAgAhCL4BCAAAAAG_AQgAAAAEwAEIAAAABMEBCAAAAAHCAQgAAAABwwEIAAAAAcQBCAAAAAHIAQgAnwIAIQ4GAACcAgAgGQAAoQIAIBoAAKECACC-AQEAAAABvwEBAAAABcABAQAAAAXBAQEAAAABwgEBAAAAAcMBAQAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAKACACELvgEBAAAAAb8BAQAAAAXAAQEAAAAFwQEBAAAAAcIBAQAAAAHDAQEAAAABxAEBAAAAAcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQChAgAhD1IAAKwCACBTAACpAgAgVAAAqgIAIFUAAKsCACC4AQAAogIAMLkBAADgAQAQugEAAKICADC7AQEAowIAIckBAQCjAgAhygEBAKQCACHLAQgApQIAIcwBAgCmAgAhzQEgAKcCACHOAQgApQIAIc8BQACoAgAhC74BAQAAAAG_AQEAAAAEwAEBAAAABMEBAQAAAAHCAQEAAAABwwEBAAAAAcQBAQAAAAHFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAkAIAIQu-AQEAAAABvwEBAAAABcABAQAAAAXBAQEAAAABwgEBAAAAAcMBAQAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAKECACEIvgEIAAAAAb8BCAAAAATAAQgAAAAEwQEIAAAAAcIBCAAAAAHDAQgAAAABxAEIAAAAAcgBCACfAgAhCL4BAgAAAAG_AQIAAAAFwAECAAAABcEBAgAAAAHCAQIAAAABwwECAAAAAcQBAgAAAAHIAQIAnAIAIQK-ASAAAAAByAEgAJoCACEIvgFAAAAAAb8BQAAAAATAAUAAAAAEwQFAAAAAAcIBQAAAAAHDAUAAAAABxAFAAAAAAcgBQACYAgAhA9ABAABrACDRAQAAawAg0gEAAGsAIAPQAQAAeAAg0QEAAHgAINIBAAB4ACAD0AEAAHQAINEBAAB0ACDSAQAAdAAgA9ABAABwACDRAQAAcAAg0gEAAHAAIAq4AQAArQIAMLkBAADaAQAQugEAAK0CADC7AQEAjQIAIbwBAQCNAgAhzwFAAJYCACHTAQEAjQIAIdQBAQCNAgAh1QECAK4CACHWAQEAkgIAIQ0GAACPAgAgGQAAjwIAIBoAAI8CACCUAQAAnwIAIJUBAACPAgAgvgECAAAAAb8BAgAAAATAAQIAAAAEwQECAAAAAcIBAgAAAAHDAQIAAAABxAECAAAAAcgBAgCvAgAhDQYAAI8CACAZAACPAgAgGgAAjwIAIJQBAACfAgAglQEAAI8CACC-AQIAAAABvwECAAAABMABAgAAAATBAQIAAAABwgECAAAAAcMBAgAAAAHEAQIAAAAByAECAK8CACEHuAEAALACADC5AQAAxAEAELoBAACwAgAwuwEBAI0CACHPAUAAlgIAIdcBAQCNAgAh2AEBAJICACEJTgAAqQIAIFIAAKwCACC4AQAAsQIAMLkBAACxAQAQugEAALECADC7AQEAowIAIc8BQACoAgAh1wEBAKMCACHYAQEApAIAIQy4AQAAsgIAMLkBAACrAQAQugEAALICADC7AQEAjQIAIbwBAQCNAgAhvQEBAI0CACHPAUAAlgIAIdQBAQCNAgAh2QFAAJYCACHaAUAAlgIAIdsBQACWAgAh3QEAALMC3QEiBwYAAI8CACAZAAC1AgAgGgAAtQIAIL4BAAAA3QECvwEAAADdAQjAAQAAAN0BCMgBAAC0At0BIgcGAACPAgAgGQAAtQIAIBoAALUCACC-AQAAAN0BAr8BAAAA3QEIwAEAAADdAQjIAQAAtALdASIEvgEAAADdAQK_AQAAAN0BCMABAAAA3QEIyAEAALUC3QEiCbgBAAC2AgAwuQEAAJUBABC6AQAAtgIAMLsBAQCNAgAhvAEBAI0CACHaAUAAlgIAIdsBQACWAgAh3gEBAI0CACHfASAAlQIAIQxNAAC6AgAgUAAAuQIAILgBAAC3AgAwuQEAAHQAELoBAAC3AgAwuwEBAKMCACG8AQEAowIAIc8BQACoAgAh0wEBAKMCACHUAQEAowIAIdUBAgC4AgAh1gEBAKQCACEIvgECAAAAAb8BAgAAAATAAQIAAAAEwQECAAAAAcIBAgAAAAHDAQIAAAABxAECAAAAAcgBAgCPAgAhEU0AALoCACBPAAC-AgAgUQAAvwIAILgBAAC8AgAwuQEAAHAAELoBAAC8AgAwuwEBAKMCACG8AQEAowIAIb0BAQCjAgAhzwFAAKgCACHUAQEAowIAIdkBQACoAgAh2gFAAKgCACHbAUAAqAIAId0BAAC9At0BIvYBAABwACD3AQAAcAAgEVIAAKwCACBTAACpAgAgVAAAqgIAIFUAAKsCACC4AQAAogIAMLkBAADgAQAQugEAAKICADC7AQEAowIAIckBAQCjAgAhygEBAKQCACHLAQgApQIAIcwBAgCmAgAhzQEgAKcCACHOAQgApQIAIc8BQACoAgAh9gEAAOABACD3AQAA4AEAIApNAAC6AgAguAEAALsCADC5AQAAeAAQugEAALsCADC7AQEAowIAIbwBAQCjAgAh2gFAAKgCACHbAUAAqAIAId4BAQCjAgAh3wEgAKcCACEPTQAAugIAIE8AAL4CACBRAAC_AgAguAEAALwCADC5AQAAcAAQugEAALwCADC7AQEAowIAIbwBAQCjAgAhvQEBAKMCACHPAUAAqAIAIdQBAQCjAgAh2QFAAKgCACHaAUAAqAIAIdsBQACoAgAh3QEAAL0C3QEiBL4BAAAA3QECvwEAAADdAQjAAQAAAN0BCMgBAAC1At0BIgtOAACpAgAgUgAArAIAILgBAACxAgAwuQEAALEBABC6AQAAsQIAMLsBAQCjAgAhzwFAAKgCACHXAQEAowIAIdgBAQCkAgAh9gEAALEBACD3AQAAsQEAIA5NAAC6AgAgUAAAuQIAILgBAAC3AgAwuQEAAHQAELoBAAC3AgAwuwEBAKMCACG8AQEAowIAIc8BQACoAgAh0wEBAKMCACHUAQEAowIAIdUBAgC4AgAh1gEBAKQCACH2AQAAdAAg9wEAAHQAIAK8AQEAAAABvQEBAAAAAQhNAAC6AgAgTwAAvgIAILgBAADBAgAwuQEAAGsAELoBAADBAgAwuwEBAKMCACG8AQEAowIAIb0BAQCjAgAhCbgBAADCAgAwuQEAAGYAELoBAADCAgAwuwEBAI0CACHPAUAAlgIAIeEBAQCNAgAh4gEBAI0CACHjAUAAlgIAIeQBQACWAgAhCbgBAADDAgAwuQEAAFMAELoBAADDAgAwuwEBAKMCACHPAUAAqAIAIeEBAQCjAgAh4gEBAKMCACHjAUAAqAIAIeQBQACoAgAhELgBAADEAgAwuQEAAE0AELoBAADEAgAwuwEBAI0CACHJAQEAjQIAIc8BQACWAgAh5AFAAJYCACHlAQEAjQIAIeYBAQCNAgAh5wEBAJICACHoAQEAkgIAIekBAQCSAgAh6gFAAMUCACHrAUAAxQIAIewBAQCSAgAh7QEBAJICACELBgAAnAIAIBkAAMcCACAaAADHAgAgvgFAAAAAAb8BQAAAAAXAAUAAAAAFwQFAAAAAAcIBQAAAAAHDAUAAAAABxAFAAAAAAcgBQADGAgAhCwYAAJwCACAZAADHAgAgGgAAxwIAIL4BQAAAAAG_AUAAAAAFwAFAAAAABcEBQAAAAAHCAUAAAAABwwFAAAAAAcQBQAAAAAHIAUAAxgIAIQi-AUAAAAABvwFAAAAABcABQAAAAAXBAUAAAAABwgFAAAAAAcMBQAAAAAHEAUAAAAAByAFAAMcCACELuAEAAMgCADC5AQAANwAQugEAAMgCADC7AQEAjQIAIckBAQCNAgAhzwFAAJYCACHjAUAAlgIAIeQBQACWAgAh7gEBAI0CACHvAQEAkgIAIfABAQCSAgAhDbgBAADJAgAwuQEAACEAELoBAADJAgAwuwEBAI0CACHPAUAAlgIAIdcBAQCNAgAh3QEBAJICACHkAUAAlgIAIfEBAQCNAgAh8gEgAJUCACHzAQEAkgIAIfQBAQCNAgAh9QEBAJICACEPBAAAywIAIAUAAMwCACC4AQAAygIAMLkBAAAOABC6AQAAygIAMLsBAQCjAgAhzwFAAKgCACHXAQEAowIAId0BAQCkAgAh5AFAAKgCACHxAQEAowIAIfIBIACnAgAh8wEBAKQCACH0AQEAowIAIfUBAQCkAgAhA9ABAAADACDRAQAAAwAg0gEAAAMAIAPQAQAABwAg0QEAAAcAINIBAAAHACARAwAAzwIAILgBAADNAgAwuQEAAAcAELoBAADNAgAwuwEBAKMCACHJAQEAowIAIc8BQACoAgAh5AFAAKgCACHlAQEAowIAIeYBAQCjAgAh5wEBAKQCACHoAQEApAIAIekBAQCkAgAh6gFAAM4CACHrAUAAzgIAIewBAQCkAgAh7QEBAKQCACEIvgFAAAAAAb8BQAAAAAXAAUAAAAAFwQFAAAAAAcIBQAAAAAHDAUAAAAABxAFAAAAAAcgBQADHAgAhEQQAAMsCACAFAADMAgAguAEAAMoCADC5AQAADgAQugEAAMoCADC7AQEAowIAIc8BQACoAgAh1wEBAKMCACHdAQEApAIAIeQBQACoAgAh8QEBAKMCACHyASAApwIAIfMBAQCkAgAh9AEBAKMCACH1AQEApAIAIfYBAAAOACD3AQAADgAgDAMAAM8CACC4AQAA0AIAMLkBAAADABC6AQAA0AIAMLsBAQCjAgAhyQEBAKMCACHPAUAAqAIAIeMBQACoAgAh5AFAAKgCACHuAQEAowIAIe8BAQCkAgAh8AEBAKQCACEAAAAB-wEBAAAAAQUTAAC4BAAgFAAAvgQAIPgBAAC5BAAg-QEAAL0EACD-AQAA3QEAIAUTAAC2BAAgFAAAuwQAIPgBAAC3BAAg-QEAALoEACD-AQAArgEAIAMTAAC4BAAg-AEAALkEACD-AQAA3QEAIAMTAAC2BAAg-AEAALcEACD-AQAArgEAIAAAAAAAAAH7AQEAAAABBfsBCAAAAAGBAggAAAABggIIAAAAAYMCCAAAAAGEAggAAAABBfsBAgAAAAGBAgIAAAABggICAAAAAYMCAgAAAAGEAgIAAAABAfsBIAAAAAEB-wFAAAAAAQsTAACbAwAwFAAAoAMAMPgBAACcAwAw-QEAAJ0DADD6AQAAngMAIPsBAACfAwAw_AEAAJ8DADD9AQAAnwMAMP4BAACfAwAw_wEAAKEDADCAAgAAogMAMAsTAACPAwAwFAAAlAMAMPgBAACQAwAw-QEAAJEDADD6AQAAkgMAIPsBAACTAwAw_AEAAJMDADD9AQAAkwMAMP4BAACTAwAw_wEAAJUDADCAAgAAlgMAMAsTAACBAwAwFAAAhgMAMPgBAACCAwAw-QEAAIMDADD6AQAAhAMAIPsBAACFAwAw_AEAAIUDADD9AQAAhQMAMP4BAACFAwAw_wEAAIcDADCAAgAAiAMAMAsTAADoAgAwFAAA7QIAMPgBAADpAgAw-QEAAOoCADD6AQAA6wIAIPsBAADsAgAw_AEAAOwCADD9AQAA7AIAMP4BAADsAgAw_wEAAO4CADCAAgAA7wIAMApPAAD_AgAgUQAAgAMAILsBAQAAAAG9AQEAAAABzwFAAAAAAdQBAQAAAAHZAUAAAAAB2gFAAAAAAdsBQAAAAAHdAQAAAN0BAgIAAAByACATAAD-AgAgAwAAAHIAIBMAAP4CACAUAADzAgAgAQwAALUEADAPTQAAugIAIE8AAL4CACBRAAC_AgAguAEAALwCADC5AQAAcAAQugEAALwCADC7AQEAAAABvAEBAKMCACG9AQEAowIAIc8BQACoAgAh1AEBAKMCACHZAUAAqAIAIdoBQACoAgAh2wFAAKgCACHdAQAAvQLdASICAAAAcgAgDAAA8wIAIAIAAADwAgAgDAAA8QIAIAy4AQAA7wIAMLkBAADwAgAQugEAAO8CADC7AQEAowIAIbwBAQCjAgAhvQEBAKMCACHPAUAAqAIAIdQBAQCjAgAh2QFAAKgCACHaAUAAqAIAIdsBQACoAgAh3QEAAL0C3QEiDLgBAADvAgAwuQEAAPACABC6AQAA7wIAMLsBAQCjAgAhvAEBAKMCACG9AQEAowIAIc8BQACoAgAh1AEBAKMCACHZAUAAqAIAIdoBQACoAgAh2wFAAKgCACHdAQAAvQLdASIIuwEBANQCACG9AQEA1AIAIc8BQADjAgAh1AEBANQCACHZAUAA4wIAIdoBQADjAgAh2wFAAOMCACHdAQAA8gLdASIB-wEAAADdAQIKTwAA9AIAIFEAAPUCACC7AQEA1AIAIb0BAQDUAgAhzwFAAOMCACHUAQEA1AIAIdkBQADjAgAh2gFAAOMCACHbAUAA4wIAId0BAADyAt0BIgUTAACrBAAgFAAAswQAIPgBAACsBAAg-QEAALIEACD-AQAArgEAIAcTAAD2AgAgFAAA-QIAIPgBAAD3AgAg-QEAAPgCACD8AQAAdAAg_QEAAHQAIP4BAAB8ACAHTQAA_QIAILsBAQAAAAG8AQEAAAABzwFAAAAAAdQBAQAAAAHVAQIAAAAB1gEBAAAAAQIAAAB8ACATAAD2AgAgAwAAAHQAIBMAAPYCACAUAAD6AgAgCQAAAHQAIAwAAPoCACBNAAD8AgAguwEBANQCACG8AQEA1AIAIc8BQADjAgAh1AEBANQCACHVAQIA-wIAIdYBAQDfAgAhB00AAPwCACC7AQEA1AIAIbwBAQDUAgAhzwFAAOMCACHUAQEA1AIAIdUBAgD7AgAh1gEBAN8CACEF-wECAAAAAYECAgAAAAGCAgIAAAABgwICAAAAAYQCAgAAAAEFEwAArQQAIBQAALAEACD4AQAArgQAIPkBAACvBAAg_gEAAN0BACADEwAArQQAIPgBAACuBAAg_gEAAN0BACAKTwAA_wIAIFEAAIADACC7AQEAAAABvQEBAAAAAc8BQAAAAAHUAQEAAAAB2QFAAAAAAdoBQAAAAAHbAUAAAAAB3QEAAADdAQIDEwAAqwQAIPgBAACsBAAg_gEAAK4BACADEwAA9gIAIPgBAAD3AgAg_gEAAHwAIAdQAACOAwAguwEBAAAAAc8BQAAAAAHTAQEAAAAB1AEBAAAAAdUBAgAAAAHWAQEAAAABAgAAAHwAIBMAAI0DACADAAAAfAAgEwAAjQMAIBQAAIsDACABDAAAqgQAMAxNAAC6AgAgUAAAuQIAILgBAAC3AgAwuQEAAHQAELoBAAC3AgAwuwEBAAAAAbwBAQCjAgAhzwFAAKgCACHTAQEAAAAB1AEBAKMCACHVAQIAuAIAIdYBAQCkAgAhAgAAAHwAIAwAAIsDACACAAAAiQMAIAwAAIoDACAKuAEAAIgDADC5AQAAiQMAELoBAACIAwAwuwEBAKMCACG8AQEAowIAIc8BQACoAgAh0wEBAKMCACHUAQEAowIAIdUBAgC4AgAh1gEBAKQCACEKuAEAAIgDADC5AQAAiQMAELoBAACIAwAwuwEBAKMCACG8AQEAowIAIc8BQACoAgAh0wEBAKMCACHUAQEAowIAIdUBAgC4AgAh1gEBAKQCACEGuwEBANQCACHPAUAA4wIAIdMBAQDUAgAh1AEBANQCACHVAQIA-wIAIdYBAQDfAgAhB1AAAIwDACC7AQEA1AIAIc8BQADjAgAh0wEBANQCACHUAQEA1AIAIdUBAgD7AgAh1gEBAN8CACEFEwAApQQAIBQAAKgEACD4AQAApgQAIPkBAACnBAAg_gEAAHIAIAdQAACOAwAguwEBAAAAAc8BQAAAAAHTAQEAAAAB1AEBAAAAAdUBAgAAAAHWAQEAAAABAxMAAKUEACD4AQAApgQAIP4BAAByACAFuwEBAAAAAdoBQAAAAAHbAUAAAAAB3gEBAAAAAd8BIAAAAAECAAAAaQAgEwAAmgMAIAMAAABpACATAACaAwAgFAAAmQMAIAEMAACkBAAwCk0AALoCACC4AQAAuwIAMLkBAAB4ABC6AQAAuwIAMLsBAQAAAAG8AQEAowIAIdoBQACoAgAh2wFAAKgCACHeAQEAowIAId8BIACnAgAhAgAAAGkAIAwAAJkDACACAAAAlwMAIAwAAJgDACAJuAEAAJYDADC5AQAAlwMAELoBAACWAwAwuwEBAKMCACG8AQEAowIAIdoBQACoAgAh2wFAAKgCACHeAQEAowIAId8BIACnAgAhCbgBAACWAwAwuQEAAJcDABC6AQAAlgMAMLsBAQCjAgAhvAEBAKMCACHaAUAAqAIAIdsBQACoAgAh3gEBAKMCACHfASAApwIAIQW7AQEA1AIAIdoBQADjAgAh2wFAAOMCACHeAQEA1AIAId8BIADiAgAhBbsBAQDUAgAh2gFAAOMCACHbAUAA4wIAId4BAQDUAgAh3wEgAOICACEFuwEBAAAAAdoBQAAAAAHbAUAAAAAB3gEBAAAAAd8BIAAAAAEDTwAA2AIAILsBAQAAAAG9AQEAAAABAgAAAG0AIBMAAKYDACADAAAAbQAgEwAApgMAIBQAAKUDACABDAAAowQAMAlNAAC6AgAgTwAAvgIAILgBAADBAgAwuQEAAGsAELoBAADBAgAwuwEBAAAAAbwBAQCjAgAhvQEBAKMCACHgAQAAwAIAIAIAAABtACAMAAClAwAgAgAAAKMDACAMAACkAwAgBrgBAACiAwAwuQEAAKMDABC6AQAAogMAMLsBAQCjAgAhvAEBAKMCACG9AQEAowIAIQa4AQAAogMAMLkBAACjAwAQugEAAKIDADC7AQEAowIAIbwBAQCjAgAhvQEBAKMCACECuwEBANQCACG9AQEA1AIAIQNPAADWAgAguwEBANQCACG9AQEA1AIAIQNPAADYAgAguwEBAAAAAb0BAQAAAAEEEwAAmwMAMPgBAACcAwAw-gEAAJ4DACD-AQAAnwMAMAQTAACPAwAw-AEAAJADADD6AQAAkgMAIP4BAACTAwAwBBMAAIEDADD4AQAAggMAMPoBAACEAwAg_gEAAIUDADAEEwAA6AIAMPgBAADpAgAw-gEAAOsCACD-AQAA7AIAMAAAAAAAAAAAAAAAAAsTAADEAwAwFAAAyAMAMPgBAADFAwAw-QEAAMYDADD6AQAAxwMAIPsBAACfAwAw_AEAAJ8DADD9AQAAnwMAMP4BAACfAwAw_wEAAMkDADCAAgAAogMAMAsTAAC5AwAwFAAAvQMAMPgBAAC6AwAw-QEAALsDADD6AQAAvAMAIPsBAADsAgAw_AEAAOwCADD9AQAA7AIAMP4BAADsAgAw_wEAAL4DADCAAgAA7wIAMApNAADDAwAgUQAAgAMAILsBAQAAAAG8AQEAAAABzwFAAAAAAdQBAQAAAAHZAUAAAAAB2gFAAAAAAdsBQAAAAAHdAQAAAN0BAgIAAAByACATAADCAwAgAwAAAHIAIBMAAMIDACAUAADAAwAgAQwAAKIEADACAAAAcgAgDAAAwAMAIAIAAADwAgAgDAAAvwMAIAi7AQEA1AIAIbwBAQDUAgAhzwFAAOMCACHUAQEA1AIAIdkBQADjAgAh2gFAAOMCACHbAUAA4wIAId0BAADyAt0BIgpNAADBAwAgUQAA9QIAILsBAQDUAgAhvAEBANQCACHPAUAA4wIAIdQBAQDUAgAh2QFAAOMCACHaAUAA4wIAIdsBQADjAgAh3QEAAPIC3QEiBRMAAJ0EACAUAACgBAAg-AEAAJ4EACD5AQAAnwQAIP4BAADdAQAgCk0AAMMDACBRAACAAwAguwEBAAAAAbwBAQAAAAHPAUAAAAAB1AEBAAAAAdkBQAAAAAHaAUAAAAAB2wFAAAAAAd0BAAAA3QECAxMAAJ0EACD4AQAAngQAIP4BAADdAQAgA00AANcCACC7AQEAAAABvAEBAAAAAQIAAABtACATAADMAwAgAwAAAG0AIBMAAMwDACAUAADLAwAgAQwAAJwEADACAAAAbQAgDAAAywMAIAIAAACjAwAgDAAAygMAIAK7AQEA1AIAIbwBAQDUAgAhA00AANUCACC7AQEA1AIAIbwBAQDUAgAhA00AANcCACC7AQEAAAABvAEBAAAAAQQTAADEAwAw-AEAAMUDADD6AQAAxwMAIP4BAACfAwAwBBMAALkDADD4AQAAugMAMPoBAAC8AwAg_gEAAOwCADAAAAAAAAAFEwAAlwQAIBQAAJoEACD4AQAAmAQAIPkBAACZBAAg_gEAAN0BACADEwAAlwQAIPgBAACYBAAg_gEAAN0BACADTQAA2AMAIE8AANkDACBRAADaAwAgBlIAAK4DACBTAACrAwAgVAAArAMAIFUAAK0DACDKAQAA2QIAIMwBAADZAgAgA04AAKsDACBSAACuAwAg2AEAANkCACADTQAA2AMAIFAAANcDACDWAQAA2QIAIAAAAAAAAAH7AUAAAAABBRMAAJIEACAUAACVBAAg-AEAAJMEACD5AQAAlAQAIP4BAAABACADEwAAkgQAIPgBAACTBAAg_gEAAAEAIAAAAAUTAACNBAAgFAAAkAQAIPgBAACOBAAg-QEAAI8EACD-AQAAAQAgAxMAAI0EACD4AQAAjgQAIP4BAAABACAAAAALEwAA-gMAMBQAAP8DADD4AQAA-wMAMPkBAAD8AwAw-gEAAP0DACD7AQAA_gMAMPwBAAD-AwAw_QEAAP4DADD-AQAA_gMAMP8BAACABAAwgAIAAIEEADALEwAA7gMAMBQAAPMDADD4AQAA7wMAMPkBAADwAwAw-gEAAPEDACD7AQAA8gMAMPwBAADyAwAw_QEAAPIDADD-AQAA8gMAMP8BAAD0AwAwgAIAAPUDADAMuwEBAAAAAc8BQAAAAAHkAUAAAAAB5QEBAAAAAeYBAQAAAAHnAQEAAAAB6AEBAAAAAekBAQAAAAHqAUAAAAAB6wFAAAAAAewBAQAAAAHtAQEAAAABAgAAAAkAIBMAAPkDACADAAAACQAgEwAA-QMAIBQAAPgDACABDAAAjAQAMBEDAADPAgAguAEAAM0CADC5AQAABwAQugEAAM0CADC7AQEAAAAByQEBAKMCACHPAUAAqAIAIeQBQACoAgAh5QEBAKMCACHmAQEAowIAIecBAQCkAgAh6AEBAKQCACHpAQEApAIAIeoBQADOAgAh6wFAAM4CACHsAQEApAIAIe0BAQCkAgAhAgAAAAkAIAwAAPgDACACAAAA9gMAIAwAAPcDACAQuAEAAPUDADC5AQAA9gMAELoBAAD1AwAwuwEBAKMCACHJAQEAowIAIc8BQACoAgAh5AFAAKgCACHlAQEAowIAIeYBAQCjAgAh5wEBAKQCACHoAQEApAIAIekBAQCkAgAh6gFAAM4CACHrAUAAzgIAIewBAQCkAgAh7QEBAKQCACEQuAEAAPUDADC5AQAA9gMAELoBAAD1AwAwuwEBAKMCACHJAQEAowIAIc8BQACoAgAh5AFAAKgCACHlAQEAowIAIeYBAQCjAgAh5wEBAKQCACHoAQEApAIAIekBAQCkAgAh6gFAAM4CACHrAUAAzgIAIewBAQCkAgAh7QEBAKQCACEMuwEBANQCACHPAUAA4wIAIeQBQADjAgAh5QEBANQCACHmAQEA1AIAIecBAQDfAgAh6AEBAN8CACHpAQEA3wIAIeoBQADhAwAh6wFAAOEDACHsAQEA3wIAIe0BAQDfAgAhDLsBAQDUAgAhzwFAAOMCACHkAUAA4wIAIeUBAQDUAgAh5gEBANQCACHnAQEA3wIAIegBAQDfAgAh6QEBAN8CACHqAUAA4QMAIesBQADhAwAh7AEBAN8CACHtAQEA3wIAIQy7AQEAAAABzwFAAAAAAeQBQAAAAAHlAQEAAAAB5gEBAAAAAecBAQAAAAHoAQEAAAAB6QEBAAAAAeoBQAAAAAHrAUAAAAAB7AEBAAAAAe0BAQAAAAEHuwEBAAAAAc8BQAAAAAHjAUAAAAAB5AFAAAAAAe4BAQAAAAHvAQEAAAAB8AEBAAAAAQIAAAAFACATAACFBAAgAwAAAAUAIBMAAIUEACAUAACEBAAgAQwAAIsEADAMAwAAzwIAILgBAADQAgAwuQEAAAMAELoBAADQAgAwuwEBAAAAAckBAQCjAgAhzwFAAKgCACHjAUAAqAIAIeQBQACoAgAh7gEBAAAAAe8BAQCkAgAh8AEBAKQCACECAAAABQAgDAAAhAQAIAIAAACCBAAgDAAAgwQAIAu4AQAAgQQAMLkBAACCBAAQugEAAIEEADC7AQEAowIAIckBAQCjAgAhzwFAAKgCACHjAUAAqAIAIeQBQACoAgAh7gEBAKMCACHvAQEApAIAIfABAQCkAgAhC7gBAACBBAAwuQEAAIIEABC6AQAAgQQAMLsBAQCjAgAhyQEBAKMCACHPAUAAqAIAIeMBQACoAgAh5AFAAKgCACHuAQEAowIAIe8BAQCkAgAh8AEBAKQCACEHuwEBANQCACHPAUAA4wIAIeMBQADjAgAh5AFAAOMCACHuAQEA1AIAIe8BAQDfAgAh8AEBAN8CACEHuwEBANQCACHPAUAA4wIAIeMBQADjAgAh5AFAAOMCACHuAQEA1AIAIe8BAQDfAgAh8AEBAN8CACEHuwEBAAAAAc8BQAAAAAHjAUAAAAAB5AFAAAAAAe4BAQAAAAHvAQEAAAAB8AEBAAAAAQQTAAD6AwAw-AEAAPsDADD6AQAA_QMAIP4BAAD-AwAwBBMAAO4DADD4AQAA7wMAMPoBAADxAwAg_gEAAPIDADAAAAUEAACIBAAgBQAAiQQAIN0BAADZAgAg8wEAANkCACD1AQAA2QIAIAe7AQEAAAABzwFAAAAAAeMBQAAAAAHkAUAAAAAB7gEBAAAAAe8BAQAAAAHwAQEAAAABDLsBAQAAAAHPAUAAAAAB5AFAAAAAAeUBAQAAAAHmAQEAAAAB5wEBAAAAAegBAQAAAAHpAQEAAAAB6gFAAAAAAesBQAAAAAHsAQEAAAAB7QEBAAAAAQsFAACHBAAguwEBAAAAAc8BQAAAAAHXAQEAAAAB3QEBAAAAAeQBQAAAAAHxAQEAAAAB8gEgAAAAAfMBAQAAAAH0AQEAAAAB9QEBAAAAAQIAAAABACATAACNBAAgAwAAAA4AIBMAAI0EACAUAACRBAAgDQAAAA4AIAUAAO0DACAMAACRBAAguwEBANQCACHPAUAA4wIAIdcBAQDUAgAh3QEBAN8CACHkAUAA4wIAIfEBAQDUAgAh8gEgAOICACHzAQEA3wIAIfQBAQDUAgAh9QEBAN8CACELBQAA7QMAILsBAQDUAgAhzwFAAOMCACHXAQEA1AIAId0BAQDfAgAh5AFAAOMCACHxAQEA1AIAIfIBIADiAgAh8wEBAN8CACH0AQEA1AIAIfUBAQDfAgAhCwQAAIYEACC7AQEAAAABzwFAAAAAAdcBAQAAAAHdAQEAAAAB5AFAAAAAAfEBAQAAAAHyASAAAAAB8wEBAAAAAfQBAQAAAAH1AQEAAAABAgAAAAEAIBMAAJIEACADAAAADgAgEwAAkgQAIBQAAJYEACANAAAADgAgBAAA7AMAIAwAAJYEACC7AQEA1AIAIc8BQADjAgAh1wEBANQCACHdAQEA3wIAIeQBQADjAgAh8QEBANQCACHyASAA4gIAIfMBAQDfAgAh9AEBANQCACH1AQEA3wIAIQsEAADsAwAguwEBANQCACHPAUAA4wIAIdcBAQDUAgAh3QEBAN8CACHkAUAA4wIAIfEBAQDUAgAh8gEgAOICACHzAQEA3wIAIfQBAQDUAgAh9QEBAN8CACELUgAAqgMAIFMAAKcDACBVAACpAwAguwEBAAAAAckBAQAAAAHKAQEAAAABywEIAAAAAcwBAgAAAAHNASAAAAABzgEIAAAAAc8BQAAAAAECAAAA3QEAIBMAAJcEACADAAAA4AEAIBMAAJcEACAUAACbBAAgDQAAAOABACAMAACbBAAgUgAA5wIAIFMAAOQCACBVAADmAgAguwEBANQCACHJAQEA1AIAIcoBAQDfAgAhywEIAOACACHMAQIA4QIAIc0BIADiAgAhzgEIAOACACHPAUAA4wIAIQtSAADnAgAgUwAA5AIAIFUAAOYCACC7AQEA1AIAIckBAQDUAgAhygEBAN8CACHLAQgA4AIAIcwBAgDhAgAhzQEgAOICACHOAQgA4AIAIc8BQADjAgAhArsBAQAAAAG8AQEAAAABC1MAAKcDACBUAACoAwAgVQAAqQMAILsBAQAAAAHJAQEAAAABygEBAAAAAcsBCAAAAAHMAQIAAAABzQEgAAAAAc4BCAAAAAHPAUAAAAABAgAAAN0BACATAACdBAAgAwAAAOABACATAACdBAAgFAAAoQQAIA0AAADgAQAgDAAAoQQAIFMAAOQCACBUAADlAgAgVQAA5gIAILsBAQDUAgAhyQEBANQCACHKAQEA3wIAIcsBCADgAgAhzAECAOECACHNASAA4gIAIc4BCADgAgAhzwFAAOMCACELUwAA5AIAIFQAAOUCACBVAADmAgAguwEBANQCACHJAQEA1AIAIcoBAQDfAgAhywEIAOACACHMAQIA4QIAIc0BIADiAgAhzgEIAOACACHPAUAA4wIAIQi7AQEAAAABvAEBAAAAAc8BQAAAAAHUAQEAAAAB2QFAAAAAAdoBQAAAAAHbAUAAAAAB3QEAAADdAQICuwEBAAAAAb0BAQAAAAEFuwEBAAAAAdoBQAAAAAHbAUAAAAAB3gEBAAAAAd8BIAAAAAELTQAAwwMAIE8AAP8CACC7AQEAAAABvAEBAAAAAb0BAQAAAAHPAUAAAAAB1AEBAAAAAdkBQAAAAAHaAUAAAAAB2wFAAAAAAd0BAAAA3QECAgAAAHIAIBMAAKUEACADAAAAcAAgEwAApQQAIBQAAKkEACANAAAAcAAgDAAAqQQAIE0AAMEDACBPAAD0AgAguwEBANQCACG8AQEA1AIAIb0BAQDUAgAhzwFAAOMCACHUAQEA1AIAIdkBQADjAgAh2gFAAOMCACHbAUAA4wIAId0BAADyAt0BIgtNAADBAwAgTwAA9AIAILsBAQDUAgAhvAEBANQCACG9AQEA1AIAIc8BQADjAgAh1AEBANQCACHZAUAA4wIAIdoBQADjAgAh2wFAAOMCACHdAQAA8gLdASIGuwEBAAAAAc8BQAAAAAHTAQEAAAAB1AEBAAAAAdUBAgAAAAHWAQEAAAABBU4AAM0DACC7AQEAAAABzwFAAAAAAdcBAQAAAAHYAQEAAAABAgAAAK4BACATAACrBAAgC1IAAKoDACBTAACnAwAgVAAAqAMAILsBAQAAAAHJAQEAAAABygEBAAAAAcsBCAAAAAHMAQIAAAABzQEgAAAAAc4BCAAAAAHPAUAAAAABAgAAAN0BACATAACtBAAgAwAAAOABACATAACtBAAgFAAAsQQAIA0AAADgAQAgDAAAsQQAIFIAAOcCACBTAADkAgAgVAAA5QIAILsBAQDUAgAhyQEBANQCACHKAQEA3wIAIcsBCADgAgAhzAECAOECACHNASAA4gIAIc4BCADgAgAhzwFAAOMCACELUgAA5wIAIFMAAOQCACBUAADlAgAguwEBANQCACHJAQEA1AIAIcoBAQDfAgAhywEIAOACACHMAQIA4QIAIc0BIADiAgAhzgEIAOACACHPAUAA4wIAIQMAAACxAQAgEwAAqwQAIBQAALQEACAHAAAAsQEAIAwAALQEACBOAAC3AwAguwEBANQCACHPAUAA4wIAIdcBAQDUAgAh2AEBAN8CACEFTgAAtwMAILsBAQDUAgAhzwFAAOMCACHXAQEA1AIAIdgBAQDfAgAhCLsBAQAAAAG9AQEAAAABzwFAAAAAAdQBAQAAAAHZAUAAAAAB2gFAAAAAAdsBQAAAAAHdAQAAAN0BAgVSAADOAwAguwEBAAAAAc8BQAAAAAHXAQEAAAAB2AEBAAAAAQIAAACuAQAgEwAAtgQAIAtSAACqAwAgVAAAqAMAIFUAAKkDACC7AQEAAAAByQEBAAAAAcoBAQAAAAHLAQgAAAABzAECAAAAAc0BIAAAAAHOAQgAAAABzwFAAAAAAQIAAADdAQAgEwAAuAQAIAMAAACxAQAgEwAAtgQAIBQAALwEACAHAAAAsQEAIAwAALwEACBSAAC4AwAguwEBANQCACHPAUAA4wIAIdcBAQDUAgAh2AEBAN8CACEFUgAAuAMAILsBAQDUAgAhzwFAAOMCACHXAQEA1AIAIdgBAQDfAgAhAwAAAOABACATAAC4BAAgFAAAvwQAIA0AAADgAQAgDAAAvwQAIFIAAOcCACBUAADlAgAgVQAA5gIAILsBAQDUAgAhyQEBANQCACHKAQEA3wIAIcsBCADgAgAhzAECAOECACHNASAA4gIAIc4BCADgAgAhzwFAAOMCACELUgAA5wIAIFQAAOUCACBVAADmAgAguwEBANQCACHJAQEA1AIAIcoBAQDfAgAhywEIAOACACHMAQIA4QIAIc0BIADiAgAhzgEIAOACACHPAUAA4wIAIQMEBgIFCgMGAAQBAwABAQMAAQIECwAFDAAAAAADBgAJGQAKGgALAAAAAwYACRkAChoACwEDAAEBAwABAwYAEBkAERoAEgAAAAMGABAZABEaABIBAwABAQMAAQMGABcZABgaABkAAAADBgAXGQAYGgAZAAAAAwYAHxkAIBoAIQAAAAMGAB8ZACAaACEBTQAkBQYAKlJ-J1NuJVR6I1V9KAJNACRPACYDBgApTm8lUnMnA00AJE8AJlF1KAJNACRQACcCTnYAUncABFKCAQBTfwBUgAEAVYEBAAFNACQBTQAkAwYALhkALxoAMAAAAAMGAC4ZAC8aADACTQAkTwAmAk0AJE8AJgMGADUZADYaADcAAAADBgA1GQA2GgA3AAADBgA8GQA9GgA-AAAAAwYAPBkAPRoAPgJNACRQACcCTQAkUAAnBQYAQxkARhoAR5QBAESVAQBFAAAAAAAFBgBDGQBGGgBHlAEARJUBAEUAAAUGAEwZAE8aAFCUAQBNlQEATgAAAAAABQYATBkATxoAUJQBAE2VAQBOAk0AJE8AJgJNACRPACYDBgBVGQBWGgBXAAAAAwYAVRkAVhoAVwcCAQgNAQkQAQoRAQsSAQ0UAQ4WBQ8XBhAZAREbBRIcBxUdARYeARcfBRsiCBwjDB0kAh4lAh8mAiAnAiEoAiIqAiMsBSQtDSUvAiYxBScyDigzAik0Aio1BSs4Dyw5Ey06Ay47Ay88AzA9AzE-AzJAAzNCBTRDFDVFAzZHBTdIFThJAzlKAzpLBTtOFjxPGj1RGz5SGz9VG0BWG0FXG0JZG0NbBURcHEVeG0ZgBUdhHUhiG0ljG0pkBUtnHkxoIlZqI1eDASNYhAEjWYUBI1qGASNbiAEjXIoBBV2LAStejQEjX48BBWCQASxhkQEjYpIBI2OTAQVklgEtZZcBMWaYASdnmQEnaJoBJ2mbASdqnAEna54BJ2ygAQVtoQEybqMBJ2-lAQVwpgEzcacBJ3KoASdzqQEFdKwBNHWtATh2rwEmd7ABJnizASZ5tAEmerUBJnu3ASZ8uQEFfboBOX68ASZ_vgEFgAG_ATqBAcABJoIBwQEmgwHCAQWEAcUBO4UBxgE_hgHHASiHAcgBKIgByQEoiQHKASiKAcsBKIsBzQEojAHPAQWNAdABQI4B0gEojwHUAQWQAdUBQZEB1gEokgHXASiTAdgBBZYB2wFClwHcAUiYAd4BJJkB3wEkmgHiASSbAeMBJJwB5AEknQHmASSeAegBBZ8B6QFJoAHrASShAe0BBaIB7gFKowHvASSkAfABJKUB8QEFpgH0AUunAfUBUagB9gElqQH3ASWqAfgBJasB-QElrAH6ASWtAfwBJa4B_gEFrwH_AVKwAYECJbEBgwIFsgGEAlOzAYUCJbQBhgIltQGHAgW2AYoCVLcBiwJY"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  trustedOrigins: [process.env.APP_URL],
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "USER",
        required: true
      },
      phone: {
        type: "string",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE"
      }
    }
  },
  socialProviders: {
    google: {
      prompt: "select_account consent",
      accessType: "offline",
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: false
  }
});

// src/app.ts
import cors from "cors";

// src/modules/tutor/tutor.route.ts
import { Router } from "express";

// src/modules/tutor/tutor.service.ts
var createTutor = async (data, userId) => {
  const existingTutor = await prisma.tutor.findUnique({ where: { userId } });
  if (existingTutor) {
    throw new Error("Tutor profile already exists.");
  }
  return await prisma.tutor.create({
    data: {
      ...data,
      userId
    }
  });
};
var updateTutorProfile = async (userId, data) => {
  return await prisma.tutor.update({
    where: { userId },
    data
  });
};
var getAllTutors = async (payload) => {
  const andConditions = [];
  if (payload.search) {
    const users = await prisma.user.findMany({
      where: {
        name: {
          contains: payload.search,
          mode: "insensitive"
        }
      },
      select: { id: true }
    });
    const userIds = users.map((u) => u.id);
    andConditions.push({
      userId: { in: userIds }
    });
  }
  if (payload.categoryId) {
    andConditions.push({
      subjects: {
        some: {
          categoryId: payload.categoryId
        }
      }
    });
  }
  if (typeof payload.isFeatured === "boolean") {
    andConditions.push({
      isFeatured: payload.isFeatured
    });
  }
  const tutors = await prisma.tutor.findMany({
    take: payload.limit,
    skip: payload.skip,
    where: {
      AND: andConditions
    },
    orderBy: {
      [payload.sortBy]: payload.sortOrder
    },
    include: {
      subjects: {
        include: {
          category: true
        }
      },
      _count: {
        select: { reviews: true, bookings: true }
      }
    }
  });
  const total = await prisma.tutor.count({
    where: { AND: andConditions }
  });
  const tutorUserIds = tutors.map((t) => t.userId);
  const userRecords = await prisma.user.findMany({
    where: { id: { in: tutorUserIds } },
    select: { id: true, name: true, image: true }
  });
  const enrichedTutors = tutors.map((tutor) => {
    const user = userRecords.find((u) => u.id === tutor.userId);
    return {
      ...tutor,
      user: user || null
    };
  });
  return {
    tutors: enrichedTutors,
    pagination: {
      total,
      page: payload.page,
      limit: payload.limit,
      totalPages: Math.ceil(total / payload.limit)
    }
  };
};
var getTutorById = async (id) => {
  const tutor = await prisma.tutor.findUniqueOrThrow({
    where: { id },
    include: {
      subjects: { include: { category: true } },
      availability: {
        where: { isBooked: false },
        orderBy: [{ day: "asc" }, { startTime: "asc" }]
      },
      reviews: {
        orderBy: { createdAt: "desc" }
      }
    }
  });
  const tutorUser = await prisma.user.findUnique({
    where: { id: tutor.userId },
    select: { id: true, name: true, email: true, image: true }
  });
  const studentIds = tutor.reviews.map((r) => r.studentId);
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, name: true, image: true }
  });
  const enrichedReviews = tutor.reviews.map((review) => ({
    ...review,
    student: students.find((s) => s.id === review.studentId) || null
  }));
  return {
    ...tutor,
    user: tutorUser || null,
    reviews: enrichedReviews
  };
};
var tutorService = {
  createTutor,
  updateTutorProfile,
  getAllTutors,
  getTutorById
};

// src/helpers/paginationSortingHelper.ts
var paginationSortingHelper = (options) => {
  const page = Number(options.page) || 1;
  const limit = Number(options.limit) || 10;
  const skip = (page - 1) * limit;
  const sortBy = options.sortBy || "createdAt";
  const sortOrder = options.sortOrder || "desc";
  return {
    page,
    limit,
    skip,
    sortBy,
    sortOrder
  };
};
var paginationSortingHelper_default = paginationSortingHelper;

// src/modules/tutor/tutor.controller.ts
var createTutor2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await tutorService.createTutor(
      req.body,
      req.user.id
    );
    res.status(201).json({
      success: true,
      message: "Tutor profile created successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateProfile = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await tutorService.updateTutorProfile(
      req.user.id,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Tutor profile updated successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllTutors2 = async (req, res, next) => {
  try {
    const { search, categoryId } = req.query;
    const searchString = typeof search === "string" ? search : void 0;
    const categoryString = typeof categoryId === "string" ? categoryId : void 0;
    const isFeatured = req.query.isFeatured ? req.query.isFeatured === "true" : void 0;
    const { page, limit, skip, sortBy, sortOrder } = paginationSortingHelper_default(
      req.query
    );
    const result = await tutorService.getAllTutors({
      search: searchString,
      categoryId: categoryString,
      isFeatured,
      page,
      limit,
      skip,
      sortBy,
      sortOrder
    });
    res.status(200).json({
      success: true,
      message: "Tutors retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getTutorById2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await tutorService.getTutorById(id);
    res.status(200).json({
      success: true,
      message: "Tutor retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var tutorController = {
  createTutor: createTutor2,
  updateProfile,
  getAllTutors: getAllTutors2,
  getTutorById: getTutorById2
};

// src/middleware/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "You are not authorized"
        });
      }
      req.user = {
        id: session.user.id,
        email: session.user.email,
        name: session.user.name,
        role: session.user.role,
        emailVerified: session.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden! You don't have permission to access this resource."
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth2;

// src/modules/tutor/tutor.route.ts
var router = Router();
router.get("/", tutorController.getAllTutors);
router.get("/:id", tutorController.getTutorById);
router.post("/", auth_default("USER" /* USER */), tutorController.createTutor);
router.put("/profile", auth_default("USER" /* USER */), tutorController.updateProfile);
var tutorRouter = router;

// src/modules/category/category.route.ts
import { Router as Router2 } from "express";

// src/modules/category/category.service.ts
var createCategory = async (data) => {
  const isExist = await prisma.category.findUnique({
    where: { name: data.name }
  });
  if (isExist) {
    throw new Error("Category with this name already exists.");
  }
  return await prisma.category.create({
    data
  });
};
var getAllCategories = async (payload) => {
  const andConditions = [];
  if (payload.search) {
    andConditions.push({
      name: {
        contains: payload.search,
        mode: "insensitive"
      }
    });
  }
  const result = await prisma.category.findMany({
    take: payload.limit,
    skip: payload.skip,
    where: {
      AND: andConditions
    },
    orderBy: {
      [payload.sortBy]: payload.sortOrder
    },
    include: {
      _count: {
        select: {
          tutors: true,
          bookings: true
        }
      }
    }
  });
  const total = await prisma.category.count({
    where: {
      AND: andConditions
    }
  });
  return {
    categories: result,
    pagination: {
      total,
      page: payload.page,
      limit: payload.limit,
      totalPages: Math.ceil(total / payload.limit)
    }
  };
};
var getCategoryById = async (id) => {
  return await prisma.category.findUniqueOrThrow({
    where: {
      id
    },
    include: {
      _count: {
        select: {
          tutors: true,
          bookings: true
        }
      }
    }
  });
};
var updateCategory = async (id, data) => {
  return await prisma.category.update({
    where: { id },
    data
  });
};
var deleteCategory = async (id) => {
  return await prisma.category.delete({
    where: { id }
  });
};
var categoryService = {
  createCategory,
  getAllCategories,
  getCategoryById,
  updateCategory,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res, next) => {
  try {
    const result = await categoryService.createCategory(req.body);
    res.status(201).json({
      success: true,
      message: "Category created successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllCategories2 = async (req, res, next) => {
  try {
    const { search } = req.query;
    const searchString = typeof search === "string" ? search : void 0;
    const { page, limit, skip, sortBy, sortOrder } = paginationSortingHelper_default(
      req.query
    );
    const result = await categoryService.getAllCategories({
      search: searchString,
      page,
      limit,
      skip,
      sortBy,
      sortOrder
    });
    res.status(200).json({
      success: true,
      message: "Categories retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getCategoryById2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await categoryService.getCategoryById(id);
    res.status(200).json({
      success: true,
      message: "Category retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateCategory2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await categoryService.updateCategory(id, req.body);
    res.status(200).json({
      success: true,
      message: "Category updated successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var deleteCategory2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await categoryService.deleteCategory(id);
    res.status(200).json({
      success: true,
      message: "Category deleted successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var categoryController = {
  createCategory: createCategory2,
  getAllCategories: getAllCategories2,
  getCategoryById: getCategoryById2,
  updateCategory: updateCategory2,
  deleteCategory: deleteCategory2
};

// src/modules/category/category.route.ts
var router2 = Router2();
router2.get("/", categoryController.getAllCategories);
router2.get("/:id", categoryController.getCategoryById);
router2.post("/", auth_default("ADMIN" /* ADMIN */), categoryController.createCategory);
router2.patch("/:id", auth_default("ADMIN" /* ADMIN */), categoryController.updateCategory);
router2.delete("/:id", auth_default("ADMIN" /* ADMIN */), categoryController.deleteCategory);
var categoryRouter = router2;

// src/modules/availability/availability.route.ts
import { Router as Router3 } from "express";

// src/modules/availability/availability.service.ts
var createAvailability = async (userId, data) => {
  const tutor = await prisma.tutor.findUnique({
    where: { userId }
  });
  if (!tutor) {
    throw new Error("Tutor profile not found. Please create a profile first.");
  }
  return await prisma.availability.create({
    data: {
      tutorId: tutor.id,
      day: data.day,
      startTime: new Date(data.startTime),
      endTime: new Date(data.endTime)
    }
  });
};
var getMyAvailability = async (userId) => {
  const tutor = await prisma.tutor.findUniqueOrThrow({
    where: { userId }
  });
  return await prisma.availability.findMany({
    where: { tutorId: tutor.id },
    orderBy: [
      { day: "asc" },
      { startTime: "asc" }
    ]
  });
};
var getTutorAvailabilityPublic = async (tutorId) => {
  return await prisma.availability.findMany({
    where: {
      tutorId,
      isBooked: false
    },
    orderBy: [
      { day: "asc" },
      { startTime: "asc" }
    ]
  });
};
var deleteAvailability = async (userId, availabilityId) => {
  const tutor = await prisma.tutor.findUniqueOrThrow({
    where: { userId }
  });
  const slot = await prisma.availability.findUniqueOrThrow({
    where: { id: availabilityId }
  });
  if (slot.tutorId !== tutor.id) {
    throw new Error("You are not authorized to delete this time slot.");
  }
  if (slot.isBooked) {
    throw new Error("Cannot delete a slot that is already booked by a student.");
  }
  return await prisma.availability.delete({
    where: { id: availabilityId }
  });
};
var availabilityService = {
  createAvailability,
  getMyAvailability,
  getTutorAvailabilityPublic,
  deleteAvailability
};

// src/modules/availability/availability.controller.ts
var createAvailability2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await availabilityService.createAvailability(
      req.user.id,
      req.body
    );
    res.status(201).json({
      success: true,
      message: "Availability slot created successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getMyAvailability2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await availabilityService.getMyAvailability(req.user.id);
    res.status(200).json({
      success: true,
      message: "Your availability retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getTutorAvailabilityPublic2 = async (req, res, next) => {
  try {
    const { tutorId } = req.params;
    const result = await availabilityService.getTutorAvailabilityPublic(tutorId);
    res.status(200).json({
      success: true,
      message: "Tutor availability retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var deleteAvailability2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const { id } = req.params;
    const result = await availabilityService.deleteAvailability(
      req.user.id,
      id
    );
    res.status(200).json({
      success: true,
      message: "Availability slot deleted successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var availabilityController = {
  createAvailability: createAvailability2,
  getMyAvailability: getMyAvailability2,
  getTutorAvailabilityPublic: getTutorAvailabilityPublic2,
  deleteAvailability: deleteAvailability2
};

// src/modules/availability/availability.route.ts
var router3 = Router3();
router3.get(
  "/tutor/:tutorId",
  availabilityController.getTutorAvailabilityPublic
);
router3.post(
  "/",
  auth_default("TUTOR" /* TUTOR */),
  availabilityController.createAvailability
);
router3.get(
  "/my-availability",
  auth_default("TUTOR" /* TUTOR */),
  availabilityController.getMyAvailability
);
router3.delete(
  "/:id",
  auth_default("TUTOR" /* TUTOR */),
  availabilityController.deleteAvailability
);
var availabilityRouter = router3;

// src/modules/booking/booking.router.ts
import { Router as Router4 } from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (studentId, payload) => {
  return await prisma.$transaction(async (tx) => {
    const slot = await tx.availability.findUniqueOrThrow({
      where: { id: payload.availabilityId }
    });
    if (slot.isBooked) {
      throw new Error("This time slot has already been booked by another student.");
    }
    const booking = await tx.booking.create({
      data: {
        studentId,
        tutorId: slot.tutorId,
        categoryId: payload.categoryId,
        date: new Date(payload.date),
        startTime: slot.startTime,
        endTime: slot.endTime,
        status: "CONFIRMED"
      }
    });
    await tx.availability.update({
      where: { id: slot.id },
      data: { isBooked: true }
    });
    return booking;
  });
};
var getMyBookings = async (userId) => {
  const tutorProfile = await prisma.tutor.findUnique({
    where: { userId }
  });
  const orConditions = [{ studentId: userId }];
  if (tutorProfile) {
    orConditions.push({ tutorId: tutorProfile.id });
  }
  const bookings = await prisma.booking.findMany({
    where: {
      OR: orConditions
    },
    orderBy: [
      { date: "desc" },
      { startTime: "desc" }
    ],
    include: {
      category: true,
      tutor: true
    }
  });
  const userIdsToFetch = /* @__PURE__ */ new Set();
  bookings.forEach((b) => {
    userIdsToFetch.add(b.studentId);
    userIdsToFetch.add(b.tutor.userId);
  });
  const users = await prisma.user.findMany({
    where: { id: { in: Array.from(userIdsToFetch) } },
    select: { id: true, name: true, email: true, image: true }
  });
  return bookings.map((booking) => {
    return {
      ...booking,
      student: users.find((u) => u.id === booking.studentId) || null,
      tutor: {
        ...booking.tutor,
        user: users.find((u) => u.id === booking.tutor.userId) || null
      }
    };
  });
};
var updateBookingStatus = async (bookingId, userId, status) => {
  const booking = await prisma.booking.findUniqueOrThrow({
    where: { id: bookingId },
    include: { tutor: true }
  });
  if (booking.studentId !== userId && booking.tutor.userId !== userId) {
    throw new Error("You are not authorized to update this booking.");
  }
  return await prisma.booking.update({
    where: { id: bookingId },
    data: { status }
  });
};
var bookingService = {
  createBooking,
  getMyBookings,
  updateBookingStatus
};

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await bookingService.createBooking(
      req.user.id,
      req.body
    );
    res.status(201).json({
      success: true,
      message: "Booking confirmed successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getMyBookings2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const result = await bookingService.getMyBookings(req.user.id);
    res.status(200).json({
      success: true,
      message: "Bookings retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateBookingStatus2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const { id } = req.params;
    const { status } = req.body;
    const result = await bookingService.updateBookingStatus(
      id,
      req.user.id,
      status
    );
    res.status(200).json({
      success: true,
      message: `Booking status updated to ${status}.`,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var bookingController = {
  createBooking: createBooking2,
  getMyBookings: getMyBookings2,
  updateBookingStatus: updateBookingStatus2
};

// src/modules/booking/booking.router.ts
var router4 = Router4();
router4.post(
  "/",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */),
  bookingController.createBooking
);
router4.get(
  "/my-bookings",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */),
  bookingController.getMyBookings
);
router4.patch(
  "/:id/status",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */),
  bookingController.updateBookingStatus
);
var bookingRouter = router4;

// src/modules/tutorSubject/tutorSubject.route.ts
import { Router as Router5 } from "express";

// src/modules/tutorSubject/tutorSubject.service.ts
var addSubject = async (userId, categoryId) => {
  const tutor = await prisma.tutor.findUnique({
    where: { userId }
  });
  if (!tutor) {
    throw new Error("Tutor profile not found. Please create a profile first.");
  }
  const existingSubject = await prisma.tutorSubject.findUnique({
    where: {
      tutorId_categoryId: {
        tutorId: tutor.id,
        categoryId
      }
    }
  });
  if (existingSubject) {
    throw new Error("You have already added this subject to your profile.");
  }
  return await prisma.tutorSubject.create({
    data: {
      tutorId: tutor.id,
      categoryId
    },
    include: {
      category: true
    }
  });
};
var removeSubject = async (userId, categoryId) => {
  const tutor = await prisma.tutor.findUnique({
    where: { userId }
  });
  if (!tutor) {
    throw new Error("Tutor profile not found.");
  }
  const existingSubject = await prisma.tutorSubject.findUnique({
    where: {
      tutorId_categoryId: {
        tutorId: tutor.id,
        categoryId
      }
    }
  });
  if (!existingSubject) {
    throw new Error("This subject is not attached to your profile.");
  }
  return await prisma.tutorSubject.delete({
    where: {
      tutorId_categoryId: {
        tutorId: tutor.id,
        categoryId
      }
    }
  });
};
var tutorSubjectService = {
  addSubject,
  removeSubject
};

// src/modules/tutorSubject/tutorSubject.controller.ts
var addSubject2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const { categoryId } = req.body;
    if (!categoryId) {
      return res.status(400).json({ success: false, message: "categoryId is required." });
    }
    const result = await tutorSubjectService.addSubject(
      req.user.id,
      categoryId
    );
    res.status(201).json({
      success: true,
      message: "Subject added to your profile successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var removeSubject2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const { categoryId } = req.query;
    const categoryString = typeof categoryId === "string" ? categoryId : void 0;
    if (!categoryString) {
      return res.status(400).json({ success: false, message: "categoryId is required." });
    }
    const result = await tutorSubjectService.removeSubject(
      req.user.id,
      categoryString
    );
    res.status(200).json({
      success: true,
      message: "Subject removed from your profile successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var tutorSubjectController = {
  addSubject: addSubject2,
  removeSubject: removeSubject2
};

// src/modules/tutorSubject/tutorSubject.route.ts
var router5 = Router5();
router5.post("/", auth_default("USER" /* USER */, "TUTOR" /* TUTOR */), tutorSubjectController.addSubject);
router5.delete("/:categoryId", auth_default("TUTOR" /* TUTOR */), tutorSubjectController.removeSubject);
var tutorSubjectRouter = router5;

// src/modules/review/review.route.ts
import { Router as Router6 } from "express";

// src/modules/review/review.service.ts
var createReview = async (studentId, payload) => {
  return await prisma.$transaction(async (tx) => {
    const booking = await tx.booking.findUniqueOrThrow({
      where: { id: payload.bookingId }
    });
    if (booking.studentId !== studentId) {
      throw new Error("You can only review your own bookings.");
    }
    if (booking.status !== "COMPLETED") {
      throw new Error(
        "You can only leave a review after the session is completed."
      );
    }
    const existingReview = await tx.review.findUnique({
      where: { bookingId: payload.bookingId }
    });
    if (existingReview) {
      throw new Error("You have already reviewed this session.");
    }
    const review = await tx.review.create({
      data: {
        bookingId: payload.bookingId,
        studentId,
        tutorId: booking.tutorId,
        rating: payload.rating,
        comment: payload.comment ?? null
      }
    });
    const aggregations = await tx.review.aggregate({
      where: { tutorId: booking.tutorId },
      _avg: {
        rating: true
      }
    });
    await tx.tutor.update({
      where: { id: booking.tutorId },
      data: {
        ratingAvg: aggregations._avg.rating || payload.rating
      }
    });
    return review;
  });
};
var getTutorReviews = async (tutorId, payload) => {
  const reviews = await prisma.review.findMany({
    where: { tutorId },
    take: payload.limit,
    skip: payload.skip,
    orderBy: { createdAt: "desc" }
  });
  const total = await prisma.review.count({ where: { tutorId } });
  const studentIds = reviews.map((r) => r.studentId);
  const students = await prisma.user.findMany({
    where: { id: { in: studentIds } },
    select: { id: true, name: true, image: true }
  });
  const enrichedReviews = reviews.map((review) => {
    return {
      ...review,
      student: students.find((s) => s.id === review.studentId) || null
    };
  });
  return {
    reviews: enrichedReviews,
    pagination: {
      total,
      page: payload.page,
      limit: payload.limit,
      totalPages: Math.ceil(total / payload.limit)
    }
  };
};
var reviewService = {
  createReview,
  getTutorReviews
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res, next) => {
  try {
    if (!req.user) {
      return res.status(401).json({ success: false, message: "Unauthorized!" });
    }
    const { bookingId, rating, comment } = req.body;
    if (!bookingId || !rating || rating < 1 || rating > 5) {
      return res.status(400).json({
        success: false,
        message: "A valid bookingId and a rating between 1 and 5 are required."
      });
    }
    const result = await reviewService.createReview(req.user.id, {
      bookingId,
      rating,
      comment
    });
    res.status(201).json({
      success: true,
      message: "Review submitted successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getTutorReviews2 = async (req, res, next) => {
  try {
    const { tutorId } = req.params;
    const { page, limit, skip } = paginationSortingHelper_default(req.query);
    const result = await reviewService.getTutorReviews(tutorId, {
      page,
      limit,
      skip
    });
    res.status(200).json({
      success: true,
      message: "Reviews retrieved successfully.",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var reviewController = {
  createReview: createReview2,
  getTutorReviews: getTutorReviews2
};

// src/modules/review/review.route.ts
var router6 = Router6();
router6.get("/tutor/:tutorId", reviewController.getTutorReviews);
router6.post(
  "/",
  auth_default("USER" /* USER */, "STUDENT" /* STUDENT */),
  reviewController.createReview
);
var reviewRouter = router6;

// src/app.ts
var app = express();
app.use(
  cors({
    origin: process.env.APP_URL || "http://localhost:4000",
    credentials: true
  })
);
app.use(express.json());
app.all("/api/auth/{*any}", toNodeHandler(auth));
app.use("/api/v1/tutors", tutorRouter);
app.use("/api/v1/categories", categoryRouter);
app.use("/api/v1/availability", availabilityRouter);
app.use("/api/v1/bookings", bookingRouter);
app.use("/api/v1/tutor-subjects", tutorSubjectRouter);
app.use("/api/v1/reviews", reviewRouter);
app.get("/", (req, res) => {
  res.send("SkillBridge web is cooking...");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
